autocommit 2021-11-27

diff --git a/local/bin/new b/local/bin/new
--- a/local/bin/new
+++ b/local/bin/new
@@ -1,8 +1,15 @@
 #!/usr/bin/env sh
 [ $# -lt 2 ] && echo "Usage: new <type> <name>\nAborted" && exit 1
 
-[ -f "$2" ] && echo "File '$2' exists!" && exit 1
+BOIL=~/.local/share/boilerplates/$1
 
-cp -r ~/.local/share/boilerplates/$1 $2 || echo "Error: '$1' not found."
+if [ -f "$BOIL" ]; then DEST="$2.$1"; else DEST="$2"; fi
 
-{ cd $2 || exit 1; ./new.sh $2; rm new.sh; } 2>/dev/null
+[ -f "$DEST" ] && echo "File '$DEST' exists!" && exit 1
+
+cp -rn $BOIL $DEST || echo "Error: '$1' not found."
+
+if [ -d "$2" ]; then
+    ./new.sh $2
+    rm new.sh
+fi
